global:
  scrape_interval: '20s'
  scrape_timeout:  '10s'
  evaluation_interval: '1m'
  external_labels:
    cluster: '{{ config["domain"] }}'

rule_files:
  - '/conf/rules/rules.yml'

scrape_configs:
  - job_name: 'lbdock'
    file_sd_configs:
    - files:
      - '/conf/targets/lbdock.yml'
